/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlPropiedades.java
 *
 * Created on 12-mar-2011, 3:23:28
 */

package ontologias.interfaz.panel;

import java.util.Iterator;
import javax.swing.JFrame;
import ontologias.utils.Ontologia;

/**
 *
 * @author Sergio
 */
public class PnlPropiedades extends javax.swing.JPanel {

    public static void main(String [] args) {
        Ontologia.getInstance();

        PnlPropiedades p = new PnlPropiedades("Pau_Gasol");
        javax.swing.JFrame window = new javax.swing.JFrame("");
        window.getContentPane().add(p);
        window.pack();
        //window.setSize(300, 600);
        window.setVisible(true);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /** Creates new form PnlPropiedades */
    public PnlPropiedades(String instanceName) {
        this.instanceName = instanceName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlPropiedades = new PanelArbolPropiedades(instanceName, this);
        jPnlInstancias = new PanelArbolInstancias(null, "", "", this);

        javax.swing.GroupLayout jPnlPropiedadesLayout = new javax.swing.GroupLayout(jPnlPropiedades);
        jPnlPropiedades.setLayout(jPnlPropiedadesLayout);
        jPnlPropiedadesLayout.setHorizontalGroup(
            jPnlPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPnlPropiedadesLayout.setVerticalGroup(
            jPnlPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPnlInstanciasLayout = new javax.swing.GroupLayout(jPnlInstancias);
        jPnlInstancias.setLayout(jPnlInstanciasLayout);
        jPnlInstanciasLayout.setHorizontalGroup(
            jPnlInstanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPnlInstanciasLayout.setVerticalGroup(
            jPnlInstanciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnlInstancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlPropiedades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlInstancias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPnlInstancias;
    private javax.swing.JPanel jPnlPropiedades;
    // End of variables declaration//GEN-END:variables

    private String instanceName;

    void actualizarPanelPropiedades() {
        ((PanelArbolPropiedades)jPnlPropiedades).actualizarPanelPropiedades();
    }

    void actualizarPanelInstancias(Iterator<String> ancestors, String propertyName, String sourceInstance) {
        ((PanelArbolInstancias)jPnlInstancias).actualizarPanelInstancias(ancestors, propertyName, sourceInstance);
    }
}
